services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

#TBD, how to make that work..
  # backend:
  #   image: inza124/main-backend:latest
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "5000:8080"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Docker
  #     MaIN__ModelsPath: /app/Models
  #   volumes:
  #     - C:\MAIN.Models:/app/Models  # Mount the directory into the container
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  blazor:
    image: inza124/main-blazor:latest
    container_name: blazor
    restart: always
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      API_URL: http://host.docker.internal:5000
      DEMO_API_URL: http://demo:8080

  demo:
    image: inza124/main-demo
    container_name: demo
    restart: always
    ports:
      - "5002:8080"
    depends_on:
      - blazor
    environment:
      LocalHost: http://host.docker.internal

volumes:
  mongo-data:
